name: Azure ACR deployment
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: github
    steps:
      - name: Checkout code
        uses: actions/checkout@main
        
      - name: Login to Azure
      - uses: Azure/login@v2.1.0
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      -  name: Azure ACR deployment
         uses: azure/arm-deploy@v1
         with:
            subscriptionId: 48662256-1551-4a3d-8e37-335744834f2e
            resourceGroupName: Devops-RG
            template: ./main.bicep 
  
