# This is a basic workflow to help you get started with Actions

name: Azure login sample

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   
    - uses: Azure/login@v2.1.0
      with:
    # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{secrets.AZURE_CREDENTIALS}}
    - name : Azure group list 
      run: |
        az group list --output table
        az keyvault secret set --name SSHPublickey --vault-name akv-1995 --vaule "${{secrets.REGISTRY_PASSWORD}}"
     
